image: gradle:6.7

stages:
  - test
  - package
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

package:
  stage: package
  script: gradle distTar
  when: manual
  artifacts:
    when: on_success
    paths:
      - build/distributions

publish:
  stage: publish
  script: gradle publish
  when: manual
