image: gradle:6.7

stages:
  - test
  - publish
  - docker-package
  - docker-build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

publish:
  stage: publish
  script: gradle publish
  when: manual

docker-package:
  stage: docker-package
  script: gradle distTar
  when: manual
  artifacts:
    when: on_success
    paths:
      - build/distributions

docker-build:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - VERSION_NUMBER=$(ls build/distributions/*.tar|sed 's/build\/distributions\/acdt-\(.*\)\.tar/\1/')
    - cp build/distributions/acdt-*.tar docker
    - docker build -t "$CI_REGISTRY_IMAGE:$VERSION_NUMBER" docker/.
    - docker push "$CI_REGISTRY_IMAGE:$VERSION_NUMBER"

