image: gradle:6.7

stages:
  - test
  - publish
  - tag
  - docker-build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

publish:
  stage: publish
  script: gradle distTar publish
  artifacts:
    when: on_success
    paths:
      - build/distributions
  rules:
    - if: '$CI_COMMIT_BRANCH == "1-add-gitlab-ci"'
      when: manual
      allow_failure: false

tag:
  image: registry.gitlab.com/bhagenbourger/docker-alpine-git:latest
  stage: tag
  script:
    - VERSION_NUMBER=$(ls build/distributions/*.tar|sed 's/build\/distributions\/acdt-\(.*\)\.tar/\1/')
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git remote add api-origin "https://oauth2:${GITLAB_REPOSITORY_KEY}@gitlab.com/${CI_PROJECT_PATH}.git"
    - git tag -a "v${VERSION_NUMBER}" -m "Version ${VERSION_NUMBER}"
    - git push --tags api-origin
  rules:
    - if: '$CI_COMMIT_BRANCH == "1-add-gitlab-ci"'
      when: on_success
      allow_failure: false

docker-build:
  image: docker:latest
  stage: docker-build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - VERSION_NUMBER=$(ls build/distributions/*.tar|sed 's/build\/distributions\/acdt-\(.*\)\.tar/\1/')
    - cp build/distributions/acdt-*.tar docker
    - docker build -t "$CI_REGISTRY_IMAGE:$VERSION_NUMBER" docker/.
    - docker push "$CI_REGISTRY_IMAGE:$VERSION_NUMBER"
  rules:
    - if: '$CI_COMMIT_BRANCH == "1-add-gitlab-ci"'
      when: on_success
      allow_failure: false
